# Generated by Django 6.0.2 on 2026-02-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('a', 'Action'), ('c', 'Comedy'), ('d', 'Drama'), ('h', 'Horror'), ('r', 'Romance'), ('s', 'Sci-Fi'), ('t', 'Thriller'), ('f', 'Fantasy')], max_length=1, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
