# Generated by Django 6.0.2 on 2026-02-23 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(upload_to='series/posters/')),
                ('year', models.DateField()),
                ('category', models.ManyToManyField(related_name='series', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.series')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('series', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('number', models.PositiveIntegerField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('media', models.FileField(upload_to='series/episodes/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='series/thumbnails/')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='series.season')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('season', 'number')},
            },
        ),
    ]
