# Generated by Django 6.0.2 on 2026-02-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('media', models.FileField(upload_to='media/')),
                ('year', models.DateField()),
                ('category', models.ManyToManyField(related_name='movies', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['year', 'name'],
            },
        ),
    ]
